version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: rust:latest

    environment:
      TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Stable Build
          command: |
            rustc --version --verbose
            cargo build
      - run:
          name: Test
          command: cargo test --all --verbose
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
